# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CV for Eugene Mirman
given_name: Eugene
family_name: Mirman
headshot: eugene.jpg
pdf:
headline: >
  Experienced Senior VP of Pee Pee at VeriZon. 
description: >
  After over 60 years as a teleporter at a Surprise Company, I decided to try something different. So here I am, with arms wide open, ready to start my next phase in life. If you have a tech company where people pee not how you like, for lots of money and fully vested A Stock, I fix everything/ make it good for you.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.eugenemirman.com/" # the base hostname & protocol for your site

# analytics
analytics:
  tracking_id:
# social
social:
  location:
    icon: marker
    text: New York City, NY USA
  email:
    icon: mail outline
    text: info@eugenemirman.com
    href: mailto:info@eugenemirman.com
  www:
    icon: linkify
    text: www.eugenemirman.com
    href: http://www.eugenemirman.com/
  twitter:
    icon: twitter
    text: "@EugeneMirman"
    href: https://twitter.com/EugeneMirman
  linkedin:
    icon: linkedin
    text: linkedin.com/in/eugene-mirman-bb023396
    href: https://www.linkedin.com/in/eugene-mirman-bb023396/
  facebook:
    icon: facebook
    text: Eugene-Mirman-17472821218
    href: https://www.facebook.com/Eugene-Mirman-17472821218/
  instagram:
    icon: instagram
    text: eugenemirman
    href: https://www.instagram.com/eugenemirman/
  youtube:
    icon: youtube
    text: UCs6AsL_xzNdqD7EPJ0znelg
    href: https://www.youtube.com/channel/UCs6AsL_xzNdqD7EPJ0znelg

# collections
collections:
  - errata
  - publications
  - education
  - skills
  - employment

# layout settings
skill_rating_max: 3

# Build settings
markdown: kramdown
